name: master_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  uuid: ^4.5.3    #for giving unique ids to elements (specifically graph nodes)
  sqflite: ^2.4.3 #for storing the graph data
  sqflite_common_ffi: any


  path: ^1.9.1  #for getting the path to the sqflite db
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
